# hello_world.yml
---
- name: My first Ansible Hello World with variable input
  hosts: local
  vars:
    - name: "my_message"
      prompt: "Please enter your custom message for the playbook:"
      private: no # Set to 'no' to show input on screen (for this example)

  tasks:
    - name: Print the custom message
      ansible.builtin.debug:
        msg: "{{ my_message }}"
