# hello_world.yml
---
- name: My first Ansible Hello World with variable input
  hosts: local
  vars:
    - name: "my_message"

  tasks:
    - name: Print the custom message
      ansible.builtin.debug:
        msg: "{{ my_message }}"
